# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:12

stages:
  - build
  - test
  - deploy

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - .yarn
    - node_modules/
    - .parcel-cache/

test:
  stage: test
  needs: []
  before_script:
      - export SHELL="bash"
      - export PATH="./node_modules/.bin:${PATH}"
  script:
    - yarn install
    - yarn test --coverage
  artifacts:
    paths:
      - dist/

# chromatic:
#   stage: deploy
#   # Sets the docker image for the job
#   image: node:12

#   # Installs the dependencies
#   before_script:
#     - yarn install --frozen-lockfile --prefer-offline --cache-folder .yarn
#   script:
#     - yarn chromatic

